INSERT INTO [TABELA DE VENDEDORES]
([MATRICULA], [NOME], [PERCENTUAL COMISSÃO])
VALUES
('00235', 'Márcio Almeida Silva', 0.8)

INSERT INTO [TABELA DE VENDEDORES]
([MATRICULA], [NOME], [PERCENTUAL COMISSÃO])
VALUES
('00236', 'Cláudia Morais', 0.8)

SELECT * FROM [TABELA DE VENDEDORES]

UPDATE [TABELA DE VENDEDORES] SET
[PERCENTUAL COMISSÃO] = 0.11
WHERE
[MATRICULA] = '00238'

UPDATE [TABELA DE VENDEDORES] SET
[NOME] = 'José Geraldo da Fonseca Junior'
WHERE
[MATRICULA] = '00233'

ALTER TABLE [TABELA DE VENDEDORES]
ALTER COLUMN [MATRICULA]
VARCHAR(5) NOT NULL

ALTER TABLE [TABELA DE VENDEDORES]
ADD CONSTRAINT PK_VENDEDORES
PRIMARY KEY CLUSTERED ([MATRICULA])



